// @ts-nocheck
import { default as __fd_glob_70 } from "../docs/security/meta.json?collection=docs"
import { default as __fd_glob_69 } from "../docs/routing/meta.json?collection=docs"
import { default as __fd_glob_68 } from "../docs/reference/openapi.yaml?collection=docs"
import { default as __fd_glob_67 } from "../docs/reference/meta.json?collection=docs"
import { default as __fd_glob_66 } from "../docs/ops/meta.json?collection=docs"
import { default as __fd_glob_65 } from "../docs/guides/meta.json?collection=docs"
import { default as __fd_glob_64 } from "../docs/frameworks/meta.json?collection=docs"
import { default as __fd_glob_63 } from "../docs/compression/meta.json?collection=docs"
import { default as __fd_glob_62 } from "../docs/architecture/meta.json?collection=docs"
import { default as __fd_glob_61 } from "../docs/meta.json?collection=docs"
import * as __fd_glob_60 from "../docs/security/STEALTH_GUIDE.md?collection=docs"
import * as __fd_glob_59 from "../docs/security/SOCKET_DEV_FINDINGS.md?collection=docs"
import * as __fd_glob_58 from "../docs/security/ROUTE_GUARD_TIERS.md?collection=docs"
import * as __fd_glob_57 from "../docs/security/PUBLIC_CREDS.md?collection=docs"
import * as __fd_glob_56 from "../docs/security/GUARDRAILS.md?collection=docs"
import * as __fd_glob_55 from "../docs/security/ERROR_SANITIZATION.md?collection=docs"
import * as __fd_glob_54 from "../docs/security/COMPLIANCE.md?collection=docs"
import * as __fd_glob_53 from "../docs/security/CLI_TOKEN_AUTH.md?collection=docs"
import * as __fd_glob_52 from "../docs/security/CLI_TOKEN.md?collection=docs"
import * as __fd_glob_51 from "../docs/routing/REASONING_REPLAY.md?collection=docs"
import * as __fd_glob_50 from "../docs/routing/QUOTA_SHARE.md?collection=docs"
import * as __fd_glob_49 from "../docs/routing/AUTO-COMBO.md?collection=docs"
import * as __fd_glob_48 from "../docs/reference/PROVIDER_REFERENCE.md?collection=docs"
import * as __fd_glob_47 from "../docs/reference/FREE_TIERS.md?collection=docs"
import * as __fd_glob_46 from "../docs/reference/ENVIRONMENT.md?collection=docs"
import * as __fd_glob_45 from "../docs/reference/CLI-TOOLS.md?collection=docs"
import * as __fd_glob_44 from "../docs/reference/API_REFERENCE.md?collection=docs"
import * as __fd_glob_43 from "../docs/ops/VM_DEPLOYMENT_GUIDE.md?collection=docs"
import * as __fd_glob_42 from "../docs/ops/TUNNELS_GUIDE.md?collection=docs"
import * as __fd_glob_41 from "../docs/ops/SQLITE_RUNTIME.md?collection=docs"
import * as __fd_glob_40 from "../docs/ops/RELEASE_CHECKLIST.md?collection=docs"
import * as __fd_glob_39 from "../docs/ops/PROXY_GUIDE.md?collection=docs"
import * as __fd_glob_38 from "../docs/ops/FLY_IO_DEPLOYMENT_GUIDE.md?collection=docs"
import * as __fd_glob_37 from "../docs/ops/E2E_DASHBOARD_SHAKEDOWN_v3.8.0.md?collection=docs"
import * as __fd_glob_36 from "../docs/ops/COVERAGE_PLAN.md?collection=docs"
import * as __fd_glob_35 from "../docs/frameworks/WEBHOOKS.md?collection=docs"
import * as __fd_glob_34 from "../docs/frameworks/TRAFFIC_INSPECTOR.md?collection=docs"
import * as __fd_glob_33 from "../docs/frameworks/SKILLS.md?collection=docs"
import * as __fd_glob_32 from "../docs/frameworks/OPENCODE.md?collection=docs"
import * as __fd_glob_31 from "../docs/frameworks/MEMORY.md?collection=docs"
import * as __fd_glob_30 from "../docs/frameworks/MCP-SERVER.md?collection=docs"
import * as __fd_glob_29 from "../docs/frameworks/GAMIFICATION.md?collection=docs"
import * as __fd_glob_28 from "../docs/frameworks/EVALS.md?collection=docs"
import * as __fd_glob_27 from "../docs/frameworks/EMBEDDED-SERVICES.md?collection=docs"
import * as __fd_glob_26 from "../docs/frameworks/CLOUD_AGENT.md?collection=docs"
import * as __fd_glob_25 from "../docs/frameworks/AGENT_PROTOCOLS_GUIDE.md?collection=docs"
import * as __fd_glob_24 from "../docs/frameworks/AGENTBRIDGE.md?collection=docs"
import * as __fd_glob_23 from "../docs/frameworks/AGENT-SKILLS.md?collection=docs"
import * as __fd_glob_22 from "../docs/frameworks/A2A-SERVER.md?collection=docs"
import * as __fd_glob_21 from "../docs/guides/USER_GUIDE.md?collection=docs"
import * as __fd_glob_20 from "../docs/guides/UNINSTALL.md?collection=docs"
import * as __fd_glob_19 from "../docs/guides/TROUBLESHOOTING.md?collection=docs"
import * as __fd_glob_18 from "../docs/guides/TERMUX_GUIDE.md?collection=docs"
import * as __fd_glob_17 from "../docs/guides/SETUP_GUIDE.md?collection=docs"
import * as __fd_glob_16 from "../docs/guides/PWA_GUIDE.md?collection=docs"
import * as __fd_glob_15 from "../docs/guides/KIRO_SETUP.md?collection=docs"
import * as __fd_glob_14 from "../docs/guides/I18N.md?collection=docs"
import * as __fd_glob_13 from "../docs/guides/FEATURES.md?collection=docs"
import * as __fd_glob_12 from "../docs/guides/ELECTRON_GUIDE.md?collection=docs"
import * as __fd_glob_11 from "../docs/guides/DOCKER_GUIDE.md?collection=docs"
import * as __fd_glob_10 from "../docs/compression/RTK_COMPRESSION.md?collection=docs"
import * as __fd_glob_9 from "../docs/compression/COMPRESSION_RULES_FORMAT.md?collection=docs"
import * as __fd_glob_8 from "../docs/compression/COMPRESSION_LANGUAGE_PACKS.md?collection=docs"
import * as __fd_glob_7 from "../docs/compression/COMPRESSION_GUIDE.md?collection=docs"
import * as __fd_glob_6 from "../docs/compression/COMPRESSION_ENGINES.md?collection=docs"
import * as __fd_glob_5 from "../docs/architecture/RESILIENCE_GUIDE.md?collection=docs"
import * as __fd_glob_4 from "../docs/architecture/REPOSITORY_MAP.md?collection=docs"
import * as __fd_glob_3 from "../docs/architecture/MONITORING_SECTIONS.md?collection=docs"
import * as __fd_glob_2 from "../docs/architecture/CODEBASE_DOCUMENTATION.md?collection=docs"
import * as __fd_glob_1 from "../docs/architecture/AUTHZ_GUIDE.md?collection=docs"
import * as __fd_glob_0 from "../docs/architecture/ARCHITECTURE.md?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "docs", {"meta.json": __fd_glob_61, "architecture/meta.json": __fd_glob_62, "compression/meta.json": __fd_glob_63, "frameworks/meta.json": __fd_glob_64, "guides/meta.json": __fd_glob_65, "ops/meta.json": __fd_glob_66, "reference/meta.json": __fd_glob_67, "reference/openapi.yaml": __fd_glob_68, "routing/meta.json": __fd_glob_69, "security/meta.json": __fd_glob_70, }, {"architecture/ARCHITECTURE.md": __fd_glob_0, "architecture/AUTHZ_GUIDE.md": __fd_glob_1, "architecture/CODEBASE_DOCUMENTATION.md": __fd_glob_2, "architecture/MONITORING_SECTIONS.md": __fd_glob_3, "architecture/REPOSITORY_MAP.md": __fd_glob_4, "architecture/RESILIENCE_GUIDE.md": __fd_glob_5, "compression/COMPRESSION_ENGINES.md": __fd_glob_6, "compression/COMPRESSION_GUIDE.md": __fd_glob_7, "compression/COMPRESSION_LANGUAGE_PACKS.md": __fd_glob_8, "compression/COMPRESSION_RULES_FORMAT.md": __fd_glob_9, "compression/RTK_COMPRESSION.md": __fd_glob_10, "guides/DOCKER_GUIDE.md": __fd_glob_11, "guides/ELECTRON_GUIDE.md": __fd_glob_12, "guides/FEATURES.md": __fd_glob_13, "guides/I18N.md": __fd_glob_14, "guides/KIRO_SETUP.md": __fd_glob_15, "guides/PWA_GUIDE.md": __fd_glob_16, "guides/SETUP_GUIDE.md": __fd_glob_17, "guides/TERMUX_GUIDE.md": __fd_glob_18, "guides/TROUBLESHOOTING.md": __fd_glob_19, "guides/UNINSTALL.md": __fd_glob_20, "guides/USER_GUIDE.md": __fd_glob_21, "frameworks/A2A-SERVER.md": __fd_glob_22, "frameworks/AGENT-SKILLS.md": __fd_glob_23, "frameworks/AGENTBRIDGE.md": __fd_glob_24, "frameworks/AGENT_PROTOCOLS_GUIDE.md": __fd_glob_25, "frameworks/CLOUD_AGENT.md": __fd_glob_26, "frameworks/EMBEDDED-SERVICES.md": __fd_glob_27, "frameworks/EVALS.md": __fd_glob_28, "frameworks/GAMIFICATION.md": __fd_glob_29, "frameworks/MCP-SERVER.md": __fd_glob_30, "frameworks/MEMORY.md": __fd_glob_31, "frameworks/OPENCODE.md": __fd_glob_32, "frameworks/SKILLS.md": __fd_glob_33, "frameworks/TRAFFIC_INSPECTOR.md": __fd_glob_34, "frameworks/WEBHOOKS.md": __fd_glob_35, "ops/COVERAGE_PLAN.md": __fd_glob_36, "ops/E2E_DASHBOARD_SHAKEDOWN_v3.8.0.md": __fd_glob_37, "ops/FLY_IO_DEPLOYMENT_GUIDE.md": __fd_glob_38, "ops/PROXY_GUIDE.md": __fd_glob_39, "ops/RELEASE_CHECKLIST.md": __fd_glob_40, "ops/SQLITE_RUNTIME.md": __fd_glob_41, "ops/TUNNELS_GUIDE.md": __fd_glob_42, "ops/VM_DEPLOYMENT_GUIDE.md": __fd_glob_43, "reference/API_REFERENCE.md": __fd_glob_44, "reference/CLI-TOOLS.md": __fd_glob_45, "reference/ENVIRONMENT.md": __fd_glob_46, "reference/FREE_TIERS.md": __fd_glob_47, "reference/PROVIDER_REFERENCE.md": __fd_glob_48, "routing/AUTO-COMBO.md": __fd_glob_49, "routing/QUOTA_SHARE.md": __fd_glob_50, "routing/REASONING_REPLAY.md": __fd_glob_51, "security/CLI_TOKEN.md": __fd_glob_52, "security/CLI_TOKEN_AUTH.md": __fd_glob_53, "security/COMPLIANCE.md": __fd_glob_54, "security/ERROR_SANITIZATION.md": __fd_glob_55, "security/GUARDRAILS.md": __fd_glob_56, "security/PUBLIC_CREDS.md": __fd_glob_57, "security/ROUTE_GUARD_TIERS.md": __fd_glob_58, "security/SOCKET_DEV_FINDINGS.md": __fd_glob_59, "security/STEALTH_GUIDE.md": __fd_glob_60, });